#cloud-config

users:
 - default
 - name: hadoop
   groups: [ubuntu, adm, google-sudoers]
   lock_passwd: false
   shell: /bin/bash


package_upgrade: true
package_update: true

# todo: edit disk format and mounting for additional disks!
# todo: check logs: cat /var/log/syslog | grep =====
# todo: check disks mounted w/ lsblk and df -h 
# todo: check => java -version, ssh -V, pdsh -V, gcloud version
# todo: other checks => bin/hadoop version
runcmd:
 - echo "=========download-repository========="
 - sudo -u hadoop -i git clone https://github.com/tansudasli/hadoop-sandbox.git
 - echo "=========download-files========="
 - wget "http://kozyatagi.mirror.guzel.net.tr/apache/hadoop/common/hadoop-3.2.1/hadoop-3.2.1.tar.gz" -O /hadoop-3.2.1.tar.gz
 - wget "https://archive.apache.org/dist/zookeeper/zookeeper-3.4.14/zookeeper-3.4.14.tar.gz" -O /zookeeper-3.4.14.tar.gz
 - wget "http://kozyatagi.mirror.guzel.net.tr/apache/hbase/2.2.3/hbase-2.2.3-bin.tar.gz" -O /hbase-2.2.3-bin.tar.gz
 - wget "https://ftp.itu.edu.tr/Mirror/Apache/spark/spark-3.0.0-preview2/spark-3.0.0-preview2-bin-hadoop3.2.tgz" -O /spark-3.0.0.tgz
 - echo "=========preparare-additional-disks-hdfs========="
 - sudo mkfs.ext4 -m 0 -F -E lazy_itable_init=0,lazy_journal_init=0,discard /dev/sdb
 - sudo mkdir -p /hdfs
 - sudo mount -o discard,defaults /dev/sdb /hdfs
 - sudo cp /etc/fstab /etc/fstab.backup
 - echo UUID=$(sudo blkid -s UUID -o value /dev/sdb) /hdfs ext4 discard,defaults,nofail 0 2 | sudo tee -a /etc/fstab
 - echo "=========extract-hadoop-files========="
 - sudo -u hadoop -i tar -xzf /hadoop-3.2.1.tar.gz
 - echo "=========bug-fix========="
 - echo "export PDSH_RCMD_TYPE=ssh" >> /etc/environment
 - echo "export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >> /etc/environment
 - echo "export HADOOP_HOME=/home/hadoop/hadoop-3.2.1" >> /etc/environment
 - echo PATH="$PATH:/snap/bin" >> /etc/environment
 - source /etc/environment
 - echo "=========end========="

packages:
 - openjdk-8-jre
 - pdsh
