#cloud-config

# runs only once, while instance created
# check /var/log/syslog!
runcmd:
 - [ wget, "http://kozyatagi.mirror.guzel.net.tr/apache/hadoop/common/hadoop-3.2.1/hadoop-3.2.1.tar.gz", -O, /hadoop-3.2.1.tar.gz ]
 - [ wget, "https://archive.apache.org/dist/zookeeper/zookeeper-3.4.14/zookeeper-3.4.14.tar.gz", -O, /zookeeper-3.4.14.tar.gz ]
 - [ wget, "http://kozyatagi.mirror.guzel.net.tr/apache/hbase/2.2.3/hbase-2.2.3-bin.tar.gz", -O, /hbase-2.2.3-bin.tar.gz ]
 - [ sh, -c, echo "=========helloworld'=========" ]

packages:
 - openjdk-8-jre

# package_upgrade: true
# package_update: true