#cloud-config

# todo: edit disk format and mounting for additional disks!
# todo: check /var/log/syslog!
# todo: check disks mounted w/ lsblk and df -h 
runcmd:
 - echo "=========download-files========="
 - wget "http://kozyatagi.mirror.guzel.net.tr/apache/hadoop/common/hadoop-3.2.1/hadoop-3.2.1.tar.gz" -O /hadoop-3.2.1.tar.gz
 - wget "https://archive.apache.org/dist/zookeeper/zookeeper-3.4.14/zookeeper-3.4.14.tar.gz" -O /zookeeper-3.4.14.tar.gz
 - wget "http://kozyatagi.mirror.guzel.net.tr/apache/hbase/2.2.3/hbase-2.2.3-bin.tar.gz" -O /hbase-2.2.3-bin.tar.gz
 - echo "=========preparare-additional-disks-hdfs========="
 - sudo mkfs.ext4 -m 0 -F -E lazy_itable_init=0,lazy_journal_init=0,discard /dev/sdb
 - sudo mkdir -p /hdfs
 - sudo mount -o discard,defaults /dev/sdb /hdfs
 - sudo cp /etc/fstab /etc/fstab.backup
 - echo UUID=$(sudo blkid -s UUID -o value /dev/sdb) /hdfs ext4 discard,defaults,nofail 0 2 | sudo tee -a /etc/fstab
 - echo "=========end========="

packages:
 - openjdk-8-jre

# package_upgrade: true
# package_update: true